### PR TITLE
Issues fixed by @bogdangi / Changed i18n msgid

### PR DESCRIPTION
**Pull request by dhavlik**
@bogdangi Fixed an important issue with title and description inside form view and criteria edit.

Additionally, @icemac changed the message ID of the "Search terms" label to match the existing one in plone.app.locales.

### CODE REVIEW

**Comment by rpatterson** [comment]
I'm no longer maintaining this.  Maybe y'all already knew that, but just in
case, let me know if anyone needs any sort of access I can grant to merge
PRs, upload releases, etc..

Ross

**Comment by icemac** [comment]
@rpatterson I did not know this. I already have write access to this repository, please add me to PyPI. I am `icemac` there, too.

**Comment by rpatterson** [comment]
The fallback "collective" user already has "Owner".  I've added you as
"Maintainer".  Let me know if you need more.

Ross

**Comment by icemac** [comment]
@rpatterson I'd like to configure travis for this repos but therefore I need admin rights. (Sorry to disturb you again.)

**Comment by rpatterson** [comment]
This isn't "my" repository.  IOW, it's not
https://github.com/*rpatterson*/collective.formcriteria.  So admin rights
are managed however the collective does that these days.  It looks like the
way that's done has changed since I last did it, so you'll have to figure
that out.

Ross

**Comment by icemac** [comment]
@rpatterson Thanks for the info, I'll start digging on my own.

**Pull request merged**
